---
- name: authorised key demo
  hosts: serverc
  tasks:
    - name: Set authorized key
      authorized_key:
        user: demouser
        state: present
        key: "{{ lookup('file', '/home/student/.ssh/lab_rsa.pub') }}"

