---
- name: installing a template file
  hosts: webservers
  vars:
    package_name: httpd
  tasks:
  - name: install apache
    yum:
      name: "{{ package_name }}"
      state: present 
  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: true
  - name: render(install) vhost config file
    template:
      src: vhostconf.j2
      dest: /etc/httpd/conf.d/vhost.conf
      owner: root
      group: root
      mode: 0644
    notify: restart httpd

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
