---
- hosts: all
  name: First play for install and starting the services
  tasks:
  - name: install 
    yum:
            name:
             - httpd
             - mariadb
            state: install
  - name: Start
    service:
      state: started
      name: httpd
        
